### ISSUE TITLE
alpine linux apk cannot intercept execve

### ISSUE THREAD

**Issue by forumi0721** [resin-io/qemu#2]
hi
i use your qemu and golang build bins to create alpine arm linux docker container
but it cannot intercept execve
in apk source, apk forks script #/bin/sh script using execve

**Comment by schmich** [comment]
This issue should probably be closed. This is fixed by #8, but the fix is already present in the source, see https://github.com/resin-io/qemu/blob/qemu-execve/linux-user/syscall.c#L5946.

The compiled `qemu-arm-static` binary in the [armv7hf-debian-qemu repo](https://github.com/resin-io-projects/armv7hf-debian-qemu) does not include this fix, so you'll need to build `qemu-arm-static` yourself until it's updated.

**Comment by petrosagg** [comment]
@forumi0721 @schmich This is issue is fixed with QEMU `2.9.0+resin1` [released in this repo](https://github.com/resin-io/qemu/releases/tag/v2.9.0%2Bresin1). I've also updated [resin-io-projects/armv7hf-debian-qemu](https://github.com/resin-io-projects/armv7hf-debian-qemu) and pushed the updated image to Dockerhub!
